language: groovy

script: ./grailsw refresh-dependencies --non-interactive
    && ./grailsw test-app -coverage

notifications:
  email:
    recipients:
      - grails-admin@kaleidos.net

    on_success: change
    on_failure: change

after_success:
  - coveralls
