language: groovy
jdk: oraclejdk7

script:
  - ./grailsw refresh-dependencies --non-interactive
  - ./grailsw "test-app -coverage -xml"

notifications:
  email:
    recipients:
      - grails-admin@kaleidos.net

    on_success: change
    on_failure: change

after_success:
  - ./grailsw coveralls
